### ISSUE TITLE
Angular universal so slow

### ISSUE THREAD

**Issue by jhimelymendoza** [FlavrHub/angular-universal-express-cache-engine#1]
Hi, I was doing some proofs of concept with your implementation, since I have very high waiting times in my project, it is an e-commerce and this is affecting the user experience. In my project, I have several routes and I have a question about what this implementation covers:
In the case of routes with path params, how are they defined?
Do I have to define all the routes of my application to be able to cache them?

As extra data, I have deployed the application in iis 7 with iis node. the classic example that you find on the internet to deploy angular universal with iis

**Comment by sbarbat** [comment]
Hey, this example does cache by the exact path ([see here](https://github.com/FlavrHub/angular-universal-express-cache-engine/blob/16cec6363355786126343cdb789d6496503f7e4e/express-engine.ts#L91)). But you can change that line to work with the parameters of your request.

Regarding the app speed, Angular Universal tends to be a little slow if not cached. But should be something to worry about. Have you tried to host it somewhere else?
